### ISSUE TITLE
slamback_and_rebound.py

### ISSUE THREAD

**Issue by pedrolimasi** [GeoEnergyLab-EPFL/PyFrac#20]
@Skonki No problems were observed when running from cmd, nor when running in Pycharm. 

@pedrolimasi Can you copy your error message here?

**Comment by Skonki** [comment]
It seems to be related to the Python version. 3.10+ seems not to allow for the plotting of empty arrays using Matplotlib. We need to avoid plotting if the array is empty or negative (for log scales).

**Comment by pedrolimasi** [comment]
This issue was fixed upstream on matplotlib :smile:
