### ISSUE TITLE
[bug] `examples/radial_K_symmetric` assumes toeplitz matrix, but uses ndarray

### ISSUE THREAD

**Issue by pedrolimasi** [GeoEnergyLab-EPFL/PyFrac#5]
Following a predictor-corrector advancing front scheme,
`time_step/ts_explicit_front.time_step_explicit_front` tries to call toeplitz matrix functions on the elasticity matrix, but it's an ndarray and code breaks.

The matrix was never set to be a toeplitz matrix.

**Comment by pedrolimasi** [comment]
The problem, to me, seems to be the design of matrix compression. Pyfrac has 2 options for compression: symmetric matrix, or block Toeplitz matrix.

As I understand it, Toeplitz compression supersedes the symmetric one, and is what most of GEL research with pyfrac has been using.

Setting the toeplitz flag to overwrite the symmetry flag is not the best design though, as the uninformed user may not realize that they must set 2 flags to use a symmetric matrix with no block toeplitz structure:

```python
SimulationProperties.useBlockToeplizCompression = False
SimulationProperties.symmetric = True
```

**Comment by pedrolimasi** [comment]
I tried setting toeplitz as priority anyway as a test, but the `radial_K_symmetric.py` example started complaining of division by zero errors.

**Comment by pedrolimasi** [comment]
I tried setting the symmetry flag to overwrite the toeplitz flag, but the explicit front-advancing scheme still doesn't know what to do with a non-toeplitz matrix.

**Comment by Skonki** [comment]
I discussed with Brice today, so completely removing Symmetric seems what we all agreed on. Are you still on this issue?

**Comment by pedrolimasi** [comment]
I'll close this with 2 versions.

(Already done) First one prioritizes Toeplitz and throws exception if user tries both symmetric and toeplitz compression.
(Working on it) Second one fully removes the 1/4-domain symmetry functionality.

I'll ping you as a reviewer, @Skonki,  for the pull-request.

**Comment by Skonki** [comment]
@pedrolimasi I don't think symmetry will work at all. Not even if it is not combined with toeplitz... Have you tried that?

**Comment by pedrolimasi** [comment]
Tried explicit, and predictor-corrector with symmetry, and it does not work.
Maybe implicit front advancing could?

**Comment by Skonki** [comment]
No, because the changes made where to switch C from an array to an object. And when symmetry is activated it is still an array. So it will never work.

**Comment by pedrolimasi** [comment]
Tasks:

- [x] Raise exception if attempted combined toeplitz+symmetry.
- [x] Fully remove symmetry-based code.
    - [x] Start with conditional statements (regex: `if .*sym[^p]`)
    - [x] Remove references to symmetry flag (regex: `^.*\.sym[^pl].*$`)
    - [x] Slow cleanup of remaining references (regex: `sym[^pl]`
    - [x] Delete symmetry-exclusive files
    - [x] Fix broken indirect imports
    - [ ] Run all examples to see what breaks
    - [ ] Commit, push, pull-request

**Comment by Skonki** [comment]
You just let me know what you want me to do.

**Comment by Skonki** [comment]
Great work on this, thanks a lot Pedro. What is the current state of failing examples?

**Comment by pedrolimasi** [comment]
Thank you, @Skonki. I'll close this issue as completed. For further discussion on this part of the project, see issue #8.
